# Site settings
title: The Re<strong>Science</strong> Journal
# email: your-email@domain.com
description: Reproducible Science is good.<br/>
             Replicated Science is better.
baseurl: ""                           # the subpath of your site, e.g. /blog/
url:     "http://rescience.github.io" # the base hostname & protocol for your site
twitter_username: ReScienceEds
github_username:  ReScience

# Build settings
markdown: redcarpet


# Exclude:
exclude: README.md
